/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labtest4_gradle_debug;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
	@Test
	void test() {
		//fail("test fail");
	}
}
