/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package labtest4_gradle_debug;

public class Main {
	public static void main(String[] args) {
	System.out.println("Hello World.");
}
}
